import { showToast } from './utils';
import type { CalculationResult, BillItem, TaxPreset } from './types';
import type { DBMember } from './useSession';

export const exportToPDF = (
  calculationResult: CalculationResult | null,
  receiptTitle: string,
  items: BillItem[],
  taxPresets: TaxPreset[],
  scTaxPresetId: string,
  serviceChargeRate: number,
  members: DBMember[],
  ledger: any[]
) => {
  try {
    if (!calculationResult) return showToast('Calculate split first.', 'error');
    // @ts-ignore
    if (!window.jspdf || !window.jspdf.jsPDF)
      return showToast('PDF Library failed to load.', 'error');

    // @ts-ignore
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    const customTitle = receiptTitle.trim();
    const dateStr = new Date().toLocaleDateString();
    const docTitle = customTitle ? customTitle : 'Settlement Receipt';

    // Brand Color Palette
    const primaryColor: [number, number, number] = [0, 128, 255];
    const primaryLight: [number, number, number] = [216, 235, 255];
    const darkText: [number, number, number] = [0, 30, 59];
    const mutedText: [number, number, number] = [0, 69, 137];
    const borderColor: [number, number, number] = [137, 196, 255];
    const headerFill: [number, number, number] = [216, 235, 255];

    let startY = 25;

    // --- HEADER ---
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...darkText);
    doc.text(docTitle, 14, startY);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...mutedText);
    doc.text(`Generated by Ekwly on ${dateStr}`, 14, startY + 6);

    doc.setDrawColor(...borderColor);
    doc.setLineWidth(0.5);
    doc.line(14, startY + 14, 196, startY + 14);
    startY += 28;

    // --- MASTER BILL BREAKDOWN ---
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...primaryColor);
    doc.text('MASTER BILL BREAKDOWN', 14, startY);
    startY += 6;

    const scTaxPreset = taxPresets.find((t) => t.id === scTaxPresetId);
    const masterTableData = items.map((i) => {
      const preset = taxPresets.find((t) => t.id === i.taxPresetId);
      const dynamicTaxRate = preset ? preset.rate / 100 : 0;
      const finalTotal =
        i.totalBase +
        i.totalBase * dynamicTaxRate +
        (i.applySC
          ? i.totalBase * serviceChargeRate * (1 + (scTaxPreset ? scTaxPreset.rate / 100 : 0))
          : 0);

      return [
        i.name,
        i.qty.toString(),
        `Rs. ${i.unitPrice.toFixed(2)}`,
        `${(dynamicTaxRate * 100).toFixed(1).replace(/\.0$/, '')}% ${i.applySC ? '+ SC' : ''}`,
        `Rs. ${finalTotal.toFixed(2)}`,
      ];
    });

    doc.autoTable({
      startY,
      head: [['Item', 'Qty', 'Unit Price', 'Tax & Fees', 'Total']],
      body: masterTableData,
      theme: 'grid',
      headStyles: {
        fillColor: headerFill,
        textColor: mutedText,
        fontStyle: 'bold',
        fontSize: 8,
        textTransform: 'uppercase',
      },
      bodyStyles: { textColor: darkText, fontSize: 9 },
      styles: { lineColor: borderColor, lineWidth: 0.1, cellPadding: 4 },
      columnStyles: {
        0: { fontStyle: 'bold' },
        1: { halign: 'center' },
        2: { halign: 'right' },
        3: { halign: 'center' },
        4: { halign: 'right', fontStyle: 'bold', textColor: primaryColor },
      },
      margin: { left: 14, right: 14 },
    });

    startY = (doc as any).lastAutoTable.finalY + 12;
    const { globalSummary, individualBreakdowns } = calculationResult;

    // --- SUMMARY SUB-TABLE ---
    const summaryData: any[] = [['Base Subtotal:', `Rs. ${globalSummary.subTotal.toFixed(2)}`]];
    for (const [taxName, amount] of Object.entries(globalSummary.taxBreakdown)) {
      if (amount > 0) summaryData.push([`${taxName}:`, `Rs. ${amount.toFixed(2)}`]);
    }
    if (globalSummary.serviceCharge > 0)
      summaryData.push(['Total Service Charge:', `Rs. ${globalSummary.serviceCharge.toFixed(2)}`]);
    summaryData.push([
      { content: 'Grand Total:', styles: { fontStyle: 'bold', textColor: darkText, fontSize: 12 } },
      {
        content: `Rs. ${globalSummary.grandTotal.toFixed(2)}`,
        styles: { fontStyle: 'bold', textColor: primaryColor, fontSize: 13 },
      },
    ]);

    doc.autoTable({
      startY,
      body: summaryData,
      theme: 'plain',
      styles: { fontSize: 9, textColor: mutedText, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 130, halign: 'right' },
        1: { halign: 'right', textColor: darkText, fontStyle: 'bold' },
      },
      margin: { left: 14, right: 14 },
    });

    startY = (doc as any).lastAutoTable.finalY + 16;

    // --- WHO PAID THE RESTAURANT ---
    const payers = members.filter((m) => m.paid_amount > 0);
    if (payers.length > 0) {
      if (startY > 250) {
        doc.addPage();
        startY = 25;
      }

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...primaryColor);
      doc.text('PAYMENTS TO RESTAURANT', 14, startY);
      startY += 6;

      doc.autoTable({
        startY,
        body: payers.map((m) => [m.name, `Rs. ${m.paid_amount.toFixed(2)}`]),
        theme: 'grid',
        bodyStyles: { textColor: darkText, fontSize: 9 },
        styles: { lineColor: borderColor, lineWidth: 0.1, cellPadding: 4 },
        columnStyles: { 0: { fontStyle: 'bold' }, 1: { halign: 'right', textColor: mutedText } },
        margin: { left: 14, right: 14 },
      });
      startY = (doc as any).lastAutoTable.finalY + 16;
    }

    // --- SETTLEMENT TRANSACTIONS (WHO OWES WHOM) ---
    if (ledger.length > 0) {
      if (startY > 240) {
        doc.addPage();
        startY = 25;
      }

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...primaryColor);
      doc.text('SETTLEMENT TRANSACTIONS', 14, startY);
      startY += 6;

      const ledgerTableData = ledger.map((l) => [
        { content: l.debtor_name, styles: { fontStyle: 'bold', textColor: darkText } },
        { content: 'owes', styles: { halign: 'center', textColor: mutedText, fontSize: 8 } },
        { content: l.creditor_name, styles: { fontStyle: 'bold', textColor: darkText } },
        {
          content: `Rs. ${Number(l.amount).toFixed(2)}`,
          styles: { halign: 'right', fontStyle: 'bold', textColor: primaryColor },
        },
      ]);

      doc.autoTable({
        startY,
        body: ledgerTableData,
        theme: 'grid',
        styles: { lineColor: borderColor, lineWidth: 0.1, cellPadding: 4 },
        margin: { left: 14, right: 14 },
      });
    }

    // --- INDIVIDUAL SETTLEMENTS (NEW PAGE) ---
    doc.addPage();
    startY = 25;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...primaryColor);
    doc.text('INDIVIDUAL SETTLEMENTS', 14, startY);
    startY += 10;

    Object.keys(individualBreakdowns).forEach((person) => {
      const b = individualBreakdowns[person];
      if (b.totalOwed === 0) return;
      if (startY > 230) {
        doc.addPage();
        startY = 25;
      }

      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...darkText);
      doc.text(person, 14, startY);
      startY += 4;

      const tableData: any[] = b.items.map((i) => [
        i.name,
        i.qtyString,
        `Rs. ${i.cost.toFixed(2)}`,
      ]);
      if (b.serviceCharge > 0)
        tableData.push([
          {
            content: 'Service Charge (inc. Tax)',
            styles: { textColor: mutedText, fontStyle: 'normal' },
          },
          '-',
          {
            content: `Rs. ${b.serviceCharge.toFixed(2)}`,
            styles: { textColor: mutedText, fontStyle: 'normal' },
          },
        ]);

      tableData.push([
        {
          content: 'Total Owed:',
          colSpan: 2,
          styles: {
            halign: 'right',
            fontStyle: 'bold',
            fillColor: primaryLight,
            textColor: primaryColor,
            fontSize: 10,
          },
        },
        {
          content: `Rs. ${b.totalOwed.toFixed(2)}`,
          styles: {
            fontStyle: 'bold',
            fillColor: primaryLight,
            textColor: primaryColor,
            fontSize: 10,
          },
        },
      ]);

      doc.autoTable({
        startY,
        head: [['Item Consumed', 'Qty', 'Allocated Cost']],
        body: tableData,
        theme: 'grid',
        headStyles: {
          fillColor: headerFill,
          textColor: mutedText,
          fontStyle: 'bold',
          fontSize: 8,
          textTransform: 'uppercase',
        },
        bodyStyles: { textColor: darkText, fontSize: 9 },
        styles: { lineColor: borderColor, lineWidth: 0.1, cellPadding: 4 },
        columnStyles: { 0: { fontStyle: 'bold' }, 1: { halign: 'center' }, 2: { halign: 'right' } },
        margin: { left: 14, right: 14 },
      });
      startY = (doc as any).lastAutoTable.finalY + 12;
    });

    // --- GLOBAL DECORATIONS ---
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFillColor(...primaryColor);
      doc.rect(0, 0, doc.internal.pageSize.getWidth(), 5, 'F');
      doc.setFontSize(8);
      doc.setTextColor(...mutedText);
      doc.text(
        `Page ${i} of ${pageCount}`,
        doc.internal.pageSize.getWidth() / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }

    const safeFilename = customTitle
      ? customTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()
      : `Settlement_${new Date().toISOString().slice(0, 10)}`;
    doc.save(`${safeFilename}.pdf`);
    showToast('PDF Generated Successfully!', 'success');
  } catch (error) {
    console.error(error);
    showToast('Error generating PDF.', 'error');
  }
};
